# Generated by Django 6.0.1 on 2026-02-10 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('sizechart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='core.sizechart')),
            ],
        ),
    ]
