# Generated by Django 6.0.1 on 2026-01-23 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='movement_type',
            field=models.CharField(choices=[('INITIAL', 'Estoque Inicial'), ('RESERVE', 'Reserva'), ('RELEASE', 'Liberação de Reserva'), ('SALE', 'Saída por Venda'), ('ADJUST', 'Ajuste Manual')], default='INITIAL', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockentry',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='core.orderitem'),
        ),
    ]
