# Generated by Django 6.0.1 on 2026-02-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sizes_options_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='supplier',
            field=models.BooleanField(default=False, verbose_name='Fornecedor'),
        ),
    ]
