# Generated by Django 6.0.1 on 2026-01-23 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_stockentry_movement_type_stockentry_order_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='storage',
        ),
    ]
