# Generated by Django 6.0.1 on 2026-02-13 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bankaccount_financialmovement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='balance',
        ),
    ]
