# Generated by Django 6.0.1 on 2026-02-14 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_bankaccount_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialmovement',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_movements', to='core.client'),
        ),
    ]
