# Generated by Django 6.0.1 on 2026-02-15 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_financialmovement_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parcels', models.IntegerField(default=1)),
                ('interval_days', models.IntegerField(default=30)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bankaccount')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.orders')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.paymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPaymentParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deadline', models.DateField()),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels_detail', to='core.orderpayment')),
            ],
        ),
    ]
