# Generated by Django 6.0.1 on 2026-02-15 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_orderpayment_orderpaymentparcel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderpaymentparcel',
            old_name='deadline',
            new_name='due_date',
        ),
        migrations.RemoveField(
            model_name='orderpaymentparcel',
            name='parcel',
        ),
        migrations.AddField(
            model_name='orderpaymentparcel',
            name='parcel_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.bankaccount'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='interval_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='parcels',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderpaymentparcel',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels_records', to='core.orderpayment'),
        ),
    ]
