# Generated by Django 6.0.1 on 2026-02-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_deadline_orderpaymentparcel_due_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderpaymentparcel',
            options={'ordering': ['number']},
        ),
        migrations.RenameField(
            model_name='orderpaymentparcel',
            old_name='value',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='orderpaymentparcel',
            name='parcel_number',
        ),
        migrations.AddField(
            model_name='orderpaymentparcel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderpaymentparcel',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
