# Generated by Django 6.0.1 on 2026-02-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_orderpaymentparcel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderpaymentparcel',
            options={'ordering': ['parcel_number']},
        ),
        migrations.RenameField(
            model_name='orderpaymentparcel',
            old_name='amount',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='orderpaymentparcel',
            name='number',
        ),
        migrations.AddField(
            model_name='orderpaymentparcel',
            name='parcel_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
