# Generated by Django 6.0.1 on 2026-02-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_orderpayment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
