# Generated by Django 6.0.1 on 2026-02-19 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_orderpayment_total_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ean13',
        ),
    ]
