# Generated by Django 6.0.1 on 2026-02-19 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_product_ean13'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='ean13',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
