# Generated by Django 6.0.1 on 2026-02-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_productvariant_ean13'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='ean13',
            field=models.CharField(blank=True, db_index=True, default=1, max_length=13, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
