# Generated by Django 6.0.1 on 2026-02-20 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_productvariant_ean13_alter_productvariant_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('description', models.TextField()),
                ('cest', models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='certificate_expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='business',
            name='certificate_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='city_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='complement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='country_code',
            field=models.CharField(default='1058', max_length=4),
        ),
        migrations.AddField(
            model_name='business',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='fantasy_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='municipal_registration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='nfce_csc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='nfce_csc_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='nfce_last_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='business',
            name='nfce_series',
            field=models.CharField(default='1', max_length=3),
        ),
        migrations.AddField(
            model_name='business',
            name='nfe_environment',
            field=models.IntegerField(choices=[(1, 'Produção'), (2, 'Homologação')], default=2),
        ),
        migrations.AddField(
            model_name='business',
            name='nfe_last_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='business',
            name='nfe_series',
            field=models.CharField(default='1', max_length=3),
        ),
        migrations.AddField(
            model_name='business',
            name='number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.plan'),
        ),
        migrations.AddField(
            model_name='business',
            name='state',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='state_registration',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='street',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='tax_regime',
            field=models.IntegerField(choices=[(1, 'Simples Nacional'), (2, 'Simples Nacional - Excesso Sublimite'), (3, 'Regime Normal')], null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='zip_code',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cfop',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cofins_cst',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cofins_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cofins_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='icms_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='icms_csosn',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='icms_cst',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='icms_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='icms_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ncm',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pis_cst',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pis_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pis_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orders',
            name='access_key',
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='cfop',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='document_model',
            field=models.CharField(blank=True, choices=[('55', 'NF-e'), ('65', 'NFC-e')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='finality',
            field=models.CharField(choices=[('1', 'NF-e Normal'), ('2', 'Complementar'), ('3', 'Ajuste'), ('4', 'Devolução')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='orders',
            name='freight_mode',
            field=models.CharField(choices=[('0', 'Contratação do Frete por conta do Remetente'), ('1', 'Contratação do Frete por conta do Destinatário'), ('2', 'Por conta de Terceiros'), ('9', 'Sem Frete')], default='9', max_length=1),
        ),
        migrations.AddField(
            model_name='orders',
            name='issue_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='nature_operation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='nfe_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='nfe_series',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='presence_indicator',
            field=models.CharField(choices=[('0', 'Não se aplica'), ('1', 'Operação Presencial'), ('2', 'Internet'), ('3', 'Teleatendimento'), ('9', 'Outros')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='orders',
            name='protocol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='xml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cest',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cfop_default',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(choices=[('0', 'Nacional'), ('1', 'Estrangeira - Importação Direta'), ('2', 'Estrangeira - Mercado Interno'), ('3', 'Nacional com Conteúdo Importação > 40%'), ('4', 'Nacional conforme processos produtivos'), ('5', 'Nacional Conteúdo Importação <= 40%'), ('6', 'Estrangeira - Importação Direta sem similar'), ('7', 'Estrangeira - Mercado Interno sem similar')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='business',
            name='document',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.CreateModel(
            name='ICMSOriginDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_state', models.CharField(max_length=2)),
                ('destination_state', models.CharField(max_length=2)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'unique_together': {('origin_state', 'destination_state')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='ncm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ncm'),
        ),
        migrations.CreateModel(
            name='NCMGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ncm_groups', to='core.business')),
            ],
        ),
        migrations.CreateModel(
            name='FiscalOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(choices=[('55', 'NF-e'), ('65', 'NFC-e')], max_length=2)),
                ('cfop', models.CharField(max_length=4)),
                ('icms_cst', models.CharField(blank=True, max_length=3, null=True)),
                ('icms_csosn', models.CharField(blank=True, max_length=3, null=True)),
                ('calculate_icms', models.BooleanField(default=True)),
                ('use_origin_destination_table', models.BooleanField(default=True)),
                ('pis_cst', models.CharField(blank=True, max_length=2, null=True)),
                ('pis_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cofins_cst', models.CharField(blank=True, max_length=2, null=True)),
                ('cofins_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_operations', to='core.business')),
                ('ncm_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ncmgroup')),
            ],
        ),
        migrations.CreateModel(
            name='NCMGroupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.ncmgroup')),
                ('ncm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ncm')),
            ],
            options={
                'unique_together': {('group', 'ncm')},
            },
        ),
    ]
