# Generated by Django 6.0.1 on 2026-02-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_ncm_business_certificate_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='city',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='city_code',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='business',
            name='district',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='number',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='business',
            name='state',
            field=models.CharField(default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='business',
            name='state_registration',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='business',
            name='street',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='tax_regime',
            field=models.IntegerField(choices=[(1, 'Simples Nacional'), (2, 'Simples Nacional - Excesso Sublimite'), (3, 'Regime Normal')], default=1),
        ),
        migrations.AlterField(
            model_name='business',
            name='zip_code',
            field=models.CharField(default=1, max_length=9),
        ),
    ]
