# Generated by Django 6.0.1 on 2026-02-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_business_city_alter_business_city_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='payment_type',
            field=models.IntegerField(choices=[(1, 'Dinheiro'), (2, 'Cheque'), (3, 'Cartão de Crédito'), (4, 'Cartão de Débito'), (5, 'Crédito Loja'), (10, 'Vale Alimentação'), (11, 'Vale Refeição'), (12, 'Vale Presente'), (13, 'Vale Combustível'), (14, 'Duplica'), (15, 'Boleto Bancário'), (16, 'Depósito Bancário'), (17, 'PIX'), (90, 'Sem Pagamento'), (99, 'Outros')], default=1),
        ),
        migrations.AlterField(
            model_name='business',
            name='country_code',
            field=models.CharField(default='1058', editable=False, max_length=4),
        ),
    ]
