# Generated by Django 6.0.1 on 2026-02-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_paymentmethod_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncm',
            name='category',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ncm',
            name='mono',
            field=models.BooleanField(default=False),
        ),
    ]
