# Generated by Django 6.0.1 on 2026-02-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_ncm_category_ncm_mono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncm',
            name='category',
            field=models.TextField(),
        ),
    ]
