# Generated by Django 6.0.1 on 2026-02-24 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_ncm_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ICMSOriginDestination',
        ),
    ]
