# Generated by Django 6.0.1 on 2026-02-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_delete_icmsorigindestination'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICMSOriginDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_state', models.CharField(max_length=2, verbose_name='UF Origem')),
                ('destination_state', models.CharField(max_length=2, verbose_name='UF Destino')),
                ('imported', models.BooleanField(default=False, verbose_name='Produto Importado (4%)')),
                ('interstate_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Alíquota Interestadual (%)')),
                ('internal_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Alíquota Interna Destino (%)')),
            ],
            options={
                'verbose_name': 'ICMS Origem/Destino',
                'verbose_name_plural': 'ICMS Origem/Destino',
                'db_table': 'core_icmsorigindestination',
                'unique_together': {('origin_state', 'destination_state', 'imported')},
            },
        ),
    ]
