# Generated by Django 6.0.1 on 2026-03-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_invoice_invoiceevent_invoiceitem_invoicelog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialmovement',
            name='expense_type',
            field=models.IntegerField(choices=[(1, 'Variavel'), (2, 'Fixa')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
