# Generated by Django 6.0.1 on 2026-03-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_financialmovement_expense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_users',
            field=models.PositiveIntegerField(default=1, help_text='Máximo de usuários por empresa'),
        ),
    ]
