# Generated by Django 6.0.1 on 2026-03-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_plan_max_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='has_api_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_audit_logs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_cash_flow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_dre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_financial_control',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_inventory_control',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_marketplace_integration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_multi_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_priority_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_user_permissions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_nfce_per_month',
            field=models.PositiveIntegerField(default=0, help_text='0 = ilimitado'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_nfe_per_month',
            field=models.PositiveIntegerField(default=0, help_text='0 = ilimitado'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_products',
            field=models.PositiveIntegerField(default=0, help_text='0 = ilimitado'),
        ),
        migrations.AddField(
            model_name='plan',
            name='storage_gb',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_users',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
